backend:
  name: git-gateway
  repo: Jirtuoso/jay-vitesse-blog
  branch: main
  base_url: https://api.netlify.com

media_folder: "public"
public_folder: "public"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Duration", name: "duration", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - name: "about"
        label: "About Page"
        file: "src/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
