backend:
  name: git-gateway
  repo: Jirtuoso/jay-vitesse-blog
  branch: main
  base_url: https://api.netlify.com

media_folder: "public"
public_folder: "public"

collections:
  - name: "Blog Posts"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: 'Slug', name: 'slug', widget: 'string' }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Time", name: "tag", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
